### ISSUE TITLE
Question regarding images in portrait mode

### ISSUE THREAD

**Issue by nbeaumont** [MattWilcox/Adaptive-Images#173]
Hi Matt,

I have an image whose width is  2048px and whose height is 1327px.  With a break point @480, on a device which is 320x480, I end up with a 480x312 image, which is great.
Now, with an image whose width is 1327px and whose height is 2048px, on the same device, I end up with a 742x480 image, where I would like a 312x480 image.
Is there a way to tell adaptive-images to take image orientation in consideration.

Thank you very much,

Nicolas

**Comment by MattWilcox** [comment]
You could potentially change the script so that the JS reports back the *smallest* dimension of the viewport instead of the largest, and then change the PHP to operate on height rather than width, which ought to work for you.

This isn't something very often required though so it's not something I'd put into the core project. Good luck! :)
